export const UPDATE_GRIST_CONFIG = 'UPDATE_GRIST_CONFIG'
export const UPDATE_GRIST_FETCH_HANDLER = 'UPDATE_GRIST_FETCH_HANDLER'
export const UPDATE_GRIST_CONFIG_CURRENT_NODE = 'UPDATE_GRIST_CONFIG_CURRENT_NODE'
