export const UPDATE_GRIST_CONFIG = 'UPDATE_GRIST_CONFIG'
export const UPDATE_GRIST_FETCH_HANDLER = 'UPDATE_GRIST_FETCH_HANDLER'
export const UPDATE_GRIST_CURRENT_NODE = 'UPDATE_GRIST_CURRENT_NODE'
export const UPDATE_GRIST_CURRENT_PROPERTIES = 'UPDATE_GRIST_CURRENT_PROPERTIES'
